# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Ignore all these until we move to JDK >= 17
      - dependency-name: 'org.apache.derby:*'
        versions: '>= 10.16'
      - dependency-name: 'com.google.errorprone:error_prone_core'
        versions: '>= 2.32'

      # Ignore all these until we move to Jakarta
      - dependency-name: 'org.springframework:*'
        versions: '>= 6'
      - dependency-name: 'jakarta.annotation:jakarta.annotation-api'
        versions: '>= 2'
      - dependency-name: 'jakarta.enterprise:jakarta.enterprise.cdi-api'
        versions: '>= 3'
      - dependency-name: 'jakarta.transaction:jakarta.transaction-api'
        versions: '>= 2'
      - dependency-name: 'jakarta.json:jakarta.json-api'
        versions: '>= 2'
      - dependency-name: 'jakarta.jms:jakarta.jms-api'
        versions: '>= 3'
      - dependency-name: 'jakarta.inject:jakarta.inject-api'
        versions: '>= 2'
      - dependency-name: 'jakarta.ejb:jakarta.ejb-api'
        versions: '>= 4'
      - dependency-name: 'jakarta.xml.bind:jakarta.xml.bind-api'
        versions: '>= 3'
      - dependency-name: 'jakarta.activation:jakarta.activation-api'
        versions: '>= 2'
      - dependency-name: 'org.apache.openwebbeans:*'
        versions: '>= 4'
      - dependency-name: 'org.apache.openwebbeans-arquillian:owb-arquillian-standalone'
        versions: '>= 4'
      - dependency-name: 'org.jboss.arquillian.container:arquillian-weld-embedded'
        versions: '>= 3'
      - dependency-name: 'org.apache.johnzon:johnzon-core'
        versions: '>= 2'
      - dependency-name: 'org.apache.qpid:qpid-jms-client'
        versions: '>= 2'
      - dependency-name: 'org.apache.activemq:activemq-client'
        versions: '>= 6'
      - dependency-name: 'org.eclipse.jetty:*'
        versions: '>= 11'
      - dependency-name: 'com.sun.xml.bind:*'
        versions: '>= 3'
      - dependency-name: 'jakarta.resource:jakarta.resource-api'
        versions: '>= 2'        
    open-pull-requests-limit: 10
    commit-message:
      # This prefix is added to remind committers to create a Jira for this dependency upgrade and update the branch with the actual Jira ID
      prefix: "ARTEMIS-X "
