language: java
install: true
matrix:
  include:
    - os: linux
      jdk: openjdk11
      env:
        - EXAMPLES_PROFILE="release"
    - os: linux
      jdk: openjdk17
      env:
        - EXAMPLES_PROFILE="examples,noRun"

# clean out Artemis artifacts from the cache
before_install:
- rm -rf $HOME/.m2/repository/org/apache/activemq/artemis-*

# use 'install' so smoke-tests will work
# By setting anything to org.apache.activemq.artemis.core.io.aio.AIOSequentialFileFactory.DISABLED we are disabling libaio loading on the testsuite
script: 
- set -e
- mvn -s .github/maven-settings.xml -ntp -Dorg.apache.activemq.artemis.core.io.aio.AIOSequentialFileFactory.DISABLED=AnythingNotNull -Dmaven.test.redirectTestOutputToFile=true -Derrorprone -Pdev -Pfast-tests -Ptests-CI -Pjmh -B install
- cd examples
- mvn -s ../.github/maven-settings.xml verify -P${EXAMPLES_PROFILE} -B -q

cache:
  directories:
  - $HOME/.m2
before_cache:
  - rm -rf $HOME/.m2/repository/org/apache/activemq/artemis-*
  - rm -rf $HOME/.m2/repository/org/apache/activemq/*-artemis
  - rm -rf $HOME/.m2/repository/org/apache/activemq/examples
