language: java
install: true
matrix:
  include:
    - os: linux
      jdk: openjdk8
      env:
        - EXAMPLES_PROFILE="release"
    - os: linux
      jdk: openjdk11
      env:
        - EXAMPLES_PROFILE="noRun"
    - os: linux
      jdk: openjdk14
      env:
        - EXAMPLES_PROFILE="noRun"

# clean out Artemis artifacts from the cache
before_install:
- rm -rf $HOME/.m2/repository/org/apache/activemq/artemis-*

# use 'install' so smoke-tests will work
# use '-Pextra-tests' to ensure extra-tests compiles even though they won't actually run
# By setting anything to org.apache.activemq.artemis.core.io.aio.AIOSequentialFileFactory.DISABLED we are disabling libaio loading on the testsuite
script: 
- set -e
- mvn -Dorg.apache.activemq.artemis.core.io.aio.AIOSequentialFileFactory.DISABLED=AnythingNotNull -Djdk8-errorprone -Pfast-tests -Pextra-tests -Ptests-CI -Pjmh -B install -q
- cd examples
- mvn install -P${EXAMPLES_PROFILE} -B -q

cache:
  directories:
  - $HOME/.m2
before_cache:
  - rm -rf $HOME/.m2/repository/org/apache/activemq/artemis-*
